# Shell tools — the daily-driver CLI layer.
brew "fzf"
brew "zoxide"
brew "ripgrep"
brew "bat"
brew "eza"
brew "fd"
brew "git-delta"
brew "starship"
brew "jq"
brew "tree"
brew "fastfetch"
brew "awscli"
